on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
            - name: "Build step"
              run: echo "Building the project..."
            - name: "Test step"
              run: echo "Running tests..."
    deploy:
        runs-on: ubuntu-latest
        needs: [build-test]
        steps:
            - name: Check out code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
            - name: "Deploy step"
              run: echo "Deploying the project..."