name: "My first workflow"
on: 
    issues: 
        types:
            - opened
jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
            - name: Run a one-line script
              run: echo "Hello, world!"