name: "Build across platforms and Deploy"
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [18, 20, 24]
                os: [ubuntu-latest, windows-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
            - name: "Set up Node.js"
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
              with:
                  node-version: ${{ matrix.node-version }}
            - name: "Build step"
              run: echo "Building the project on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}..."
            - name: "Test step"
              run: echo "Running tests..."
    deploy:
        runs-on: ubuntu-latest
        needs: [build-test]
        steps:
            - name: Check out code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
            - name: "Deploy step"
              run: echo "Deploying the project..."